In [3]:
import numpy as np

A = np.array([[1, 1], [2, 2], [0, 0]])

U,S,V = np.linalg.svd(A)

print(U.round(2))
print(S.round(2))
print(V.round(2))

[[-0.45 -0.89  0.  ]
 [-0.89  0.45  0.  ]
 [ 0.    0.    1.  ]]
[3.16 0.  ]
[[-0.71 -0.71]
 [-0.71  0.71]]


$$A = \begin{bmatrix} 1 & 1 \\ 2 & 2 \\ 0 & 0 \end{bmatrix} = U\Sigma V^T = \begin{bmatrix} \frac{1}{\sqrt{5}} & -\frac{2}{\sqrt{5}} & 0 \\ \frac{2}{\sqrt{5}} & \frac{1}{\sqrt{5}} & 0 \\ 0 & 0 & 1 \end{bmatrix} \begin{bmatrix} \sqrt{10} & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix} \begin{bmatrix} \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \end{bmatrix}$$

In [10]:
from sklearn.utils.extmath import randomized_svd

U, S, V = randomized_svd(A, n_components=1)
print(U.round(2))
print(S.round(2))
print(V.round(2))

[[0.45]
 [0.89]
 [0.  ]]
[3.16]
[[0.71 0.71]]


In [11]:
Sigma = np.zeros((U.shape[1], V.shape[0]))  # 3×2 的零矩阵
Sigma[:len(S), :len(S)] = np.diag(S)        # 把 S 放到对角线

print(Sigma.round(2))
A_reconstructed = (U @ Sigma) @ V
print(A_reconstructed.round(2))

[[3.16]]
[[1. 1.]
 [2. 2.]
 [0. 0.]]


原始矩阵秩为 1，所以用一个奇异值就可以完全复原

In [12]:
# PCA 在特征工程中，对特征进行降维
from sklearn.decomposition import PCA

X = np.random.randn(100, 3)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
print(X_pca.shape)

(100, 2)
