In [10]:
import numpy as np
temps = np.array([28, 30, 29, 31, 32, 30, 29])
print('平均气温', np.mean(temps).round(2))
print('最高气温', np.max(temps).round(2))
print('最低气温', np.min(temps).round(2))

print('超过 30 度的天数', len(temps[temps>30]))
print('超过 30 度的天数', np.cumsum(np.where(temps>30, 1, 0))[-1])
print('超过 30 度的天数', np.count_nonzero(np.where(temps>30)))

平均气温 29.86
最高气温 32
最低气温 28
超过 30 度的天数 2
超过 30 度的天数 2
超过 30 度的天数 2


In [17]:
scores = np.array([85, 90, 78, 92, 88])
print(scores)
print('平均分', np.mean(scores).round(1))
print('中位数', np.median(scores).round(1))
print('标准差', np.std(scores).round(2))
print('10 分制', (scores/10).round(1))

[85 90 78 92 88]
平均分 86.6
中位数 88.0
标准差 4.88
10 分制 [8.5 9.  7.8 9.2 8.8]


In [22]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6], [7, 8]])
print('A+B\n',A+B)
print('A*B\n',A*B)
print('A@B\n',A@B)
print('A@B\n',np.dot(A,B))

A+B
 [[ 6  8]
 [10 12]]
A*B
 [[ 5 12]
 [21 32]]
A@B
 [[19 22]
 [43 50]]
A@B
 [[19 22]
 [43 50]]


In [24]:
np.random.seed(0)
arr = np.random.randint(0, 10, (3, 4))
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [26]:
print('每列最大值', np.max(arr, axis=0))
print('每行最小值', np.min(arr, axis=1))

每列最大值 [7 9 7 6]
每行最小值 [0 3 2]


In [31]:
print('每行奇数替换为-1\n', np.where(arr % 2 != 0, -1, arr))
arr[arr%2==1]=-1
print(arr)

每行奇数替换为-1
 [[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [34]:
arr = np.arange(1, 13)
print(arr)
arr = np.reshape(arr, (3, 4))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
print('每行的和', np.sum(arr,axis=1))
print('每列的平均值', np.mean(arr, axis=0))

每行的和 [10 26 42]
每列的平均值 [5. 6. 7. 8.]


In [37]:
print(np.reshape(arr,(12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [44]:
# 第 5 题
np.random.seed(0)
arr = np.random.randint(0, 20, (5, 5))
print(arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]


In [45]:
print('大于10 替换为 0', np.where(arr > 10, 0, arr))
arr[arr>10] = 0
print('大于10 替换为 0', arr)

大于10 替换为 0 [[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]
大于10 替换为 0 [[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [48]:
# 第 6 题
sales = np.array([120, 135, 110, 125, 130, 140])
print('总额', np.sum(sales))
print('方差', np.var(sales).round(1))
print('均值', np.mean(sales).round(1))

总额 760
方差 97.2
均值 126.7


In [53]:
print('最高月份', np.argmax(sales)+1)
print('最低月份', np.argmin(sales)+1)

最高月份 6
最低月份 3


In [63]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print('水平拼接\n', np.concatenate([A,B]))
print('竖直拼接\n', np.array([A,B]))

水平拼接
 [1 2 3 4 5 6]
竖直拼接
 [[1 2 3]
 [4 5 6]]


In [64]:
# 9. 唯一值
arr = [2, 1, 2, 3, 1, 4, 3]

print('唯一值', np.unique(arr))

唯一值 [1 2 3 4]


In [65]:
u_arr, cnt = np.unique(arr, return_counts=True)
print(u_arr)
print(cnt)

[1 2 3 4]
[2 2 2 1]


In [70]:
# 20.
sale = np.array([20, 25, 22, 30, 28])
cost = np.array([15, 18, 16, 22, 20])

profit = sale - cost
print('每天利润', profit)
print('利润平均值', np.mean(profit).round(1), '标准差', np.std(profit).round(1))
print('利润最高的天数', len(profit[profit == np.max(profit)]))


每天利润 [5 7 6 8 8]
利润平均值 6.8 标准差 1.2
利润最高的天数 2
