# ndarray 的特性
* 多维性
* 同质性
* 高效性

## 多维性

In [1]:
import numpy as np

In [7]:
arr = np.array(5)   # 创建0维 ndarray
print(arr)
print('arr的维度',np.ndim(arr))
print('arr的维度',arr.ndim)

5
arr的维度 0
arr的维度 0


In [8]:
arr = np.array([1, 2, 3])   # 创建1维 ndarray
print(arr)
print('arr的维度',np.ndim(arr))
print('arr的维度',arr.ndim)

[1 2 3]
arr的维度 1
arr的维度 1


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])   # 创建0维 ndarray
print(arr)
print('arr的维度',np.ndim(arr))
print('arr的维度',arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度 2
arr的维度 2


## 同质性

In [10]:
arr = np.array([1, 'hello'])
print(arr)

['1' 'hello']


In [11]:
arr = np.array([1, 2.5])
print(arr)

[1.  2.5]


# ndarray 的属性

In [18]:
arr = np.array(1)
print('数组的形状', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数', arr.size)

数组的形状 ()
数组的维度 0
元素的个数 1


In [22]:
arr = np.array([1,2.5,3])
print('数组的形状', arr.shape)
print('数组的维度', arr.ndim)
print('元素的个数', arr.size)
print('元素的数据类型', arr.dtype)

数组的形状 (3,)
数组的维度 1
元素的个数 3
元素的数据类型 float64


In [24]:
arr = np.array([[1,2,3],[4,5,6]])
print('数组的形状', arr.shape)
print('元素的个数', arr.size)
print('元素的转置', arr.T)

数组的形状 (2, 3)
元素的个数 6
元素的转置 [[1 4]
 [2 5]
 [3 6]]


# ndarray 的创建

In [28]:
# 基础的创建
list1 = [4, 5, 6]
arr = np.array([[1,2,3], list1], dtype=np.float64)
print(arr.ndim)
print(arr)

2
[[1. 2. 3.]
 [4. 5. 6.]]


In [29]:
# copy
arr1 = np.copy(arr)
print(arr1)

[[1. 2. 3.]
 [4. 5. 6.]]


In [31]:
arr1[0] = 8
print(arr)
print(arr1)

[[1. 2. 3.]
 [4. 5. 6.]]
[[8. 8. 8.]
 [4. 5. 6.]]


In [34]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((3,3), dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [36]:
arr = np.zeros((2,), dtype=int)
print(arr)

[0 0]


In [37]:
# 全 1
arr = np.ones((5,8), dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [38]:
# 未初始化
arr = np.empty((2,3))   # 效率更快
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [39]:
arr = np.full((3,4), 2025, dtype=int)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [42]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr, 2026)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [46]:
# 等差数列
arr = np.arange(1, 10, 1)
print(arr)
arr = np.arange(2, 11, 2)
print(arr)

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10]


In [51]:
# 等间隔数列
arr = np.linspace(1, 10, 5)
print(arr)
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)
arr = np.arange(0, 101, 25)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]
[  0  25  50  75 100]
[  0  25  50  75 100]


In [58]:
# 对数间隔数列
arr = np.logspace(0,5,5,base=2).round(2)
print(arr)

[ 1.    2.38  5.66 13.45 32.  ]


## 矩阵

In [64]:
# 特殊矩阵
# 单位矩阵：主对角线上的数字为1，其他的数字为0
arr = np.eye(5, dtype=int)
print(arr)
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [65]:
# 对角矩阵： 主对角线上非零的0，其他数字为0
arr = np.diag([5, 1, 2, 3])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [66]:
# 随机数组的生成
# 生成 0 到 1 之间的均匀对肌肤点数（均匀分布）
arr = np.random.rand(2, 3)
print(arr)

[[0.32572378 0.64649073 0.06296304]
 [0.77775273 0.28029849 0.07137382]]


In [68]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3, 6, size=(2, 3))
print(arr)

[[3.09149363 4.36915999 4.0932551 ]
 [4.62184439 4.80458253 5.42805416]]


In [69]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30, size=(2, 3))
print(arr)

[[ 9 11  4]
 [15 24 23]]


In [74]:
# 生成随机数列（正态分布）
arr = np.random.randn(2, 3)
print(arr)

[[-1.01837363  0.22129873  0.55052778]
 [-0.17935632 -1.33063839 -1.09100629]]


In [76]:
np.random.seed(20)
arr = np.random.random((2, 3))
print(arr)
np.random.seed(20)
arr = np.random.random((2, 3))
print(arr)

[[0.5881308  0.89771373 0.89153073]
 [0.81583748 0.03588959 0.69175758]]
[[0.5881308  0.89771373 0.89153073]
 [0.81583748 0.03588959 0.69175758]]


# 索引与切片

In [78]:
arr = np.random.randint(1, 100, 20)

In [79]:
print(arr)

[62 78 84 58 95 33 11  7 76 19  4 78 18 44 17 19 80 91 60 72]


In [88]:
print(arr[10])
print(np.arange(0, 20, 1))
print(arr[:])
print(arr[2:5]) # 左包又不包
s = slice(2, 15, 3)
print(arr[s])
print(arr[(arr>50) & (arr%2==0)])

4
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[62 78 84 58 95 33 11  7 76 19  4 78 18 44 17 19 80 91 60 72]
[84 58 95]
[84 33 76 78 17]
[62 78 84 58 76 78 80 60 72]


In [89]:
# 二维数组的切片
arr = np.random.randint(1, 100, (4, 8))
print(arr)

[[76 30 46  7 64 79 25 19]
 [94 34 79 43 95  4 19 71]
 [53 23 15  5 28 76  9  7]
 [27 80 83 79 11 34 86 18]]


In [93]:
print(arr[1,3]) # 索引
print(arr[1,:])
print(arr[1,2:5])
print(arr[arr>50])  # 压缩为了一位数组

43
[94 34 79 43 95  4 19 71]
[79 43 95]
[76 64 79 94 79 95 71 53 76 80 83 79 86]


In [94]:
print(arr[2][arr[2] > 50])

[53 76]


In [95]:
print(arr)
print('取第三列',arr[:,2])

[[76 30 46  7 64 79 25 19]
 [94 34 79 43 95  4 19 71]
 [53 23 15  5 28 76  9  7]
 [27 80 83 79 11 34 86 18]]
取第三列 [46 79 15 83]


# ndarray 的运算
* 相同位置元素各自计算
* 广播机制

In [102]:
# 基础算数运算
a = np.diag([1, 2, 3])
b = np.full((3,3),1)
print('a\n',a)
print('b\n',b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

a
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
b
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 1 1]
 [1 3 1]
 [1 1 4]]
[[ 0 -1 -1]
 [-1  1 -1]
 [-1 -1  2]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [103]:
print(b * 2)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [104]:
# 广播机制
a = np.array([1, 2, 3])
b = np.array([[4],[5],[6]])
print(a+b)
"""
a (1, 3)    b (3, 1)
1 2 3       4 4 4
1 2 3       5 5 5
1 2 3       6 6 6
"""

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [105]:
# 矩阵的乘法
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
b = np.eye(3) * 2
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


In [106]:
print(a @ b)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [107]:
a = np.full((3,3), 9)
print(np.sqrt(a))

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [114]:
print(np.exp(1))
print(np.log(2.71818))

2.718281828459045
0.9999625387017254


In [116]:
# 计算sin，cos
print(np.sin(np.pi/2))
print(np.cos(0))

1.0
1.0


In [118]:
# 计算绝对值
arr = np.array([1, -2, 3])
print(np.abs(arr))
print(np.power(arr, 2))

[1 2 3]
[1 4 9]


In [119]:
# 四舍五入
print(np.round([3.5, 4.5, 5.5, 6.5])) #银行家舍入

[4. 4. 6. 6.]


In [120]:
# 向上取整，向下取整
arr = np.array([1.5, 25.1, 81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [127]:
# 检测确实值
arr = np.array([1, 2, np.nan, 3])
print(np.isnan([1, 2, np.nan, 3]))
print(np.isnan(arr))

[False False  True False]
[False False  True False]


# 统计函数
求和、平均值、中位数、标准差、方差、
查找最大值、最小值、分位数、累计和、累计差

In [128]:
arr = np.random.randint(1, 20, 8)
print(arr)

[ 9 19 11  5  9 17 17 11]


In [129]:
# 求和
print(np.sum(arr))

98


In [133]:
# 计算平均值
print(np.mean(arr))

12.25


In [135]:
# 计算中位数
# 奇数个：排序后中间数值
# 偶数个：中间的两个数的平均值
print(np.median(arr))
print(np.median([1, 2, 5, 100]))

11.0
3.5


In [139]:
# 计算标准差、方差
# 平均值 2
# (1-2)^2 + .. + (3-2)^2 / 3 = 0.666
# 标准差 = 方差 ^ 0.5
print(np.mean([1, 2, 3]))
print(np.var([1, 2, 3]))
print(np.std([1, 2, 3]))

2.0
0.6666666666666666
0.816496580927726


In [142]:
# 最值的计算
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

[ 9 19 11  5  9 17 17 11]
19 1
5 3


In [153]:
# 分位数
# 中位数
print(np.median([1, 2, 3]))
print(np.median([1, 2, 3, 4]))
arr = np.arange(1,11,1)
arr = [0, 0, 1, 2, 2, 2, 3, 4, 6, 8 ,10]
print(arr)
print(np.median(arr))
print(np.percentile(arr, 25))

2.0
2.5
[0, 0, 1, 2, 2, 2, 3, 4, 6, 8, 10]
2.0
1.5


# 比较函数

In [154]:
print(np.greater([3, 4, 5, 6, 7], 4))

[False False  True  True  True]


In [156]:
print(np.any([0,0,0,0,1]))

True


In [158]:
# 自定义条件
arr = np.array([1,2,3,4,5])
print(np.where(arr>3, arr, 0))
print(np.where(arr>3, 1, 0))

[0 0 0 4 5]
[0 0 0 1 1]


In [161]:
score = np.random.randint(50, 100, 20)
print(score)
print(np.where(
    score < 60, 'F', np.where(
        score < 80, 'B', 'A'
    )
))

[61 55 50 72 87 54 93 68 59 64 87 85 61 91 73 79 83 52 69 72]
['B' 'F' 'F' 'B' 'A' 'F' 'A' 'B' 'F' 'B' 'A' 'A' 'B' 'A' 'B' 'B' 'A' 'F'
 'B' 'B']


In [164]:
# np.select
print(np.select([score > 80, (score>=60) & (score <= 80), score < 60],
                ['A', 'B', 'F'],
                default='U'))

['B' 'F' 'F' 'B' 'A' 'F' 'A' 'B' 'F' 'B' 'A' 'A' 'B' 'A' 'B' 'B' 'A' 'F'
 'B' 'B']


In [167]:

np.random.seed(0)
arr = np.random.randint(1, 100, 20)
print(arr)
print(np.sort(arr))
print(arr)
arr.sort()
print(arr)

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]


In [168]:
# 去重
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [169]:
# 数组的拼接
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate([arr1, arr2]))

[1 2 3 4 5 6]


In [171]:
# 数组的分割
print(np.split(arr,4))
print(np.array(np.split(arr,4)))

[array([10, 13, 22, 37, 40]), array([45, 47, 48, 59, 65]), array([66, 68, 68, 71, 84]), array([88, 88, 89, 89, 89])]
[[10 13 22 37 40]
 [45 47 48 59 65]
 [66 68 68 71 84]
 [88 88 89 89 89]]


# 一些验证

(3,) (1,3) (3,1) 以及他们的广播

In [174]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3]])
c = np.array([[1],[2],[3]])
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(1, 3)
(3, 1)


In [177]:
# 广播呢？
d = b + c
b, c, d

(array([[1, 2, 3]]),
 array([[1],
        [2],
        [3]]),
 array([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]))

In [178]:
d = a + c
a, c, d

(array([1, 2, 3]),
 array([[1],
        [2],
        [3]]),
 array([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]))

In [184]:
d3 = np.array(
                [
                [[1,2],[3,4]],
                [[1,2],[3,4]],
                [[1,2],[3,4]],
                ]
)
d3.shape, d3.ndim

((3, 2, 2), 3)